services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms_ultra_frontend_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://ms_ultra_backend_dev:8000 # Connect to the backend
    networks:
      - ms_ultra_network

networks:
  ms_ultra_network:
    external: true
